### ISSUE TITLE
Running in Chrome

### ISSUE THREAD

**Issue by alex-webb** [SilverDecisions/SilverDecisions#165]
I'm having 2 console errors running file:///C:/git/silver/docs/SilverDecisions.html?lang=en in Chrome. I have cloned and run npm install and get these console errors (seems to work OK in IE):

> SilverDecisions.html?lang=en:14 GET file://www.google-analytics.com/analytics.js net::ERR_FILE_NOT_FOUND
> (anonymous) @ SilverDecisions.html?lang=en:14
> (anonymous) @ SilverDecisions.html?lang=en:15
> silver-decisions-core-1.0.0.min.js:1

> Uncaught DOMException: Failed to construct 'Worker': Script at 'file:///C:/git/silver/docs/app/gen/silverdecisions-job-worker-1.0.0.js' cannot be accessed from origin 'null'.

**Comment by mwasiluk** [comment]
Hi,

Error is caused by Web Worker, Chrome doesn't let you load web workers when running scripts from a local file. 

https://stackoverflow.com/questions/21408510/chrome-cant-load-web-worker

**Comment by alex-webb** [comment]
Thanks I'll use Firefox.  Also running gulp gives me the following error (all I've done on the repo is npm i):

> C:\git\silver\gulpfile.js:88
>             Object.getOwnPropertyNames(require('./node_modules/'+name+'/package.json').dependencies).forEach(n=>checkModule(n, true))

> TypeError: Cannot convert undefined or null to object
>     at Function.getOwnPropertyNames (<anonymous>)
>     at checkModule (C:\git\silver\gulpfile.js:88:20)
>     at Object.getOwnPropertyNames.forEach.n (C:\git\silver\gulpfile.js:88:113)
>     at Array.forEach (native)
>     at checkModule (C:\git\silver\gulpfile.js:88:102)
>     at Object.getOwnPropertyNames.forEach.n (C:\git\silver\gulpfile.js:88:113)
>     at Array.forEach (native)
>     at checkModule (C:\git\silver\gulpfile.js:88:102)
>     at Object.getOwnPropertyNames.forEach.n (C:\git\silver\gulpfile.js:71:59)
>     at Array.forEach (native)
>     at __dirname.forEach.p (C:\git\silver\gulpfile.js:71:48)
>     at Array.forEach (native)
>     at Object.<anonymous> (C:\git\silver\gulpfile.js:70:62)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
